# Generated by Django 3.0.5 on 2020-05-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainingsangebot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('add_info', models.TextField(blank=True)),
                ('sale', models.BooleanField()),
                ('category', models.CharField(choices=[('Einzel', 'Einzelstunden'), ('Abo', 'Abo'), ('Camp', 'Tenniscamp')], max_length=64)),
            ],
        ),
    ]
